Add debugging information to the flatbuffer build
I've observed multiple flatbuffers build failures when running (make -j).
Since I've been unable to reproduce locally, I'm adding some debug
information here. The build failures look like a missing header.

[ 65%] Building CXX object CMakeFiles/flatsamplebinary.dir/samples/sample_binary.cpp.o
Scanning dependencies of target flattests
[ 69%] Building CXX object CMakeFiles/flattests.dir/src/code_generators.cpp.o
[ 69%] Building CXX object CMakeFiles/flattests.dir/src/idl_parser.cpp.o
[ 71%] Building CXX object CMakeFiles/flattests.dir/src/idl_gen_text.cpp.o
/mnt/source/flatbuffers/flatbuffers-1.6.0/samples/sample_binary.cpp:19:17: error: 'MyGame' has not been declared
 using namespace MyGame::Sample;
                 ^
/mnt/source/flatbuffers/flatbuffers-1.6.0/samples/sample_binary.cpp:19:25: error: 'Sample' is not a namespace-name
 using namespace MyGame::Sample;
                         ^
/mnt/source/flatbuffers/flatbuffers-1.6.0/samples/sample_binary.cpp:19:31: error: expected namespace-name before ';' token
 using namespace MyGame::Sample;
                               ^
/mnt/source/flatbuffers/flatbuffers-1.6.0/samples/sample_binary.cpp: In function 'int main(int, const char**)':
/mnt/source/flatbuffers/flatbuffers-1.6.0/samples/sample_binary.cpp:25:3: error: 'flatbuffers' has not been declared
   flatbuffers::FlatBufferBuilder builder;
   ^
/mnt/source/flatbuffers/flatbuffers-1.6.0/samples/sample_binary.cpp:28:26: error: 'builder' was not declared in this scope
   auto weapon_one_name = builder.CreateString("Sword");
                          ^

Change-Id: I7754f808295c2454f6ba3c60a2ad44c0701148d8